### ISSUE TITLE
Consider where Code of Conduct is linked

### ISSUE THREAD

**Issue by getsource** [WordPress/hosting-handbook#1]
Right now, I've included the [CODE_OF_CONDUCT.md](https://github.com/WordPress/hosting-handbook/blob/master/CODE_OF_CONDUCT.md) verbatim from the Gutenberg/Docker/etc repos, and it is linked from [CONTRIBUTING.md](https://github.com/WordPress/hosting-handbook/blob/master/CONTRIBUTING.md) but excluded from the handbook manifest generator.

I realize the team is assumed to be included under https://wordpress.org/about/etiquette/, but figured it probably wouldn't hurt to call it out directly, too. Created this issue to discuss it.

Could be:
- Add a title to [CODE_OF_CONDUCT.md](https://github.com/WordPress/hosting-handbook/blob/master/CODE_OF_CONDUCT.md) and include it in the manifest as its own Handbook page.
- Link and mention of Code of Conduct within [Get Involved](https://github.com/WordPress/hosting-handbook/blob/master/get-involved.md) or [Handbook Index](https://github.com/WordPress/hosting-handbook/blob/master/index.md)
- Something else entirely?

**Comment by javiercasares** [comment]
If the intention is to include that in the Handbook, I think we should have pages for both Code and Contributing (also we should normalize the file name to lowercase and with hyphen -not underscores- to do some SEO and logical URL structure).

About the linking, the index page (as a final disclaimer) and the Get Involved (at the _Getting Started at Contributing_ section) are great to do that.

**Comment by javiercasares** [comment]
I think we should add that infrmation at the end of the Get Involved section...

**Comment by pfefferle** [comment]
Do we have to link it somewhere? GitHub does support that natively, isn't that enough to start?

![Bildschirmfoto 2020-11-10 um 09 45 48](https://user-images.githubusercontent.com/2373/98651213-41908e00-233a-11eb-9b5c-d97c8733dba4.png)

**Comment by javiercasares** [comment]
Linked in CONTRIBUTING.
