### ISSUE TITLE
More security measurements in security.md

### ISSUE THREAD

**Issue by Crixu** [WordPress/hosting-handbook#13]
Something which can be done for the WCEU contributor day:

How can we further improve the security of a WordPress installation from a hoster point of view? What should customers expect in case of a standard WordPress installation compared to a Managed WordPress?
Security Measurements which hosts could implement with their own "WordPress setup routines" (See https://github.com/WordPress/hosting-handbook/issues/14)?

What comes to my mind:

- Preconfigure salts and security keys
- Forbid PHP execution in some folders
- Block directory browsing
- Block hotlinking

With examples of how a .htaccess file could look like in these cases

**Comment by javiercasares** [comment]
Moved to:
https://github.com/WordPress/Advanced-administration-handbook/issues/154
