### ISSUE TITLE
PHP 8.0-8.2 should be listed as "beta support" for WP 6.2  in the Server Environment handbook page

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/hosting-handbook#159]
In the [PHP Section of the Server Environment handbook page](https://make.wordpress.org/hosting/handbook/server-environment/#php), PHP 8.0, 8.1, and 8.2 are still "beta support" for WordPress 6.2. See the Supported Version Chart in the [PHP Compatibility and WordPress Versions](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) handbook page.

This ticket requests adding the `*` and same not as in the other WordPress versions:

```
IMPORTANT: WordPress 6.2 has beta support for [PHP 8.0](https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/), [PHP 8.1](https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/) and PHP 8.2. If used some of these versions may get some Warnings.
```

**Comment by javiercasares** [comment]
Done some commits ago.
