### ISSUE TITLE
List of Learn WordPress and WordPress TV material

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#174]
Create a page for the Handbook with a list pf Learn WordPress and WordPress TV and other material created by the Community related to hosting.

That list may involve DNS, domains, hosting, backups, CDN, performance...

**Comment by subashcpoudel** [comment]
Thank you for the ticket @javiercasares I think a curated list of WP Learn, Documentation , WP TV and other resources will help any new Hosting team enthusiast like me to get started on the proper path to contributing to the team.

**Comment by javiercasares** [comment]
WordPress TV last page reviewed:
https://wordpress.tv/page/42/

**Comment by rogermedia** [comment]
@javiercasares from doing a quick search of WordPress TV for 'hosting' https://wordpress.tv/?s=hosting There are a lot of results.

Does it make sense to manually curate each entry or are we better linking to the search query URL for common terms related to hosting?

**Comment by javiercasares** [comment]
The idea is to have a curated list… there is no problem how we find the videos (if navigating, looking for keywords, etc.) so, that's a good place to start :D

**Comment by rogermedia** [comment]
@javiercasares thank you for the clarification. I can start working on this ticket.

Here are a few videos I think have good quality production and relevant information:
High level introduction to domains and hosting - https://wordpress.tv/2023/12/07/wordpress-essentials-domains-and-hosting/
How to Choose a WordPress Hosting Company - https://wordpress.tv/2020/01/21/shaan-nicol-how-to-choose-a-wordpress-hosting-company-wordpress-singapore/
How fun is DNS? - https://wordpress.tv/2021/03/30/nuutti-toivola-how-fun-is-dns/
Introducing… Domains! - https://wordpress.tv/2022/08/12/introducing-domains/
What is the Domain Name System? - https://wordpress.tv/2022/08/29/what-is-the-domain-name-system/
WordPress Backups. Disaster management and recovery - https://wordpress.tv/2018/08/09/vineet-talwar-wordpress-backups-disaster-management-and-recovery/
PERFORMANCE 101 - https://wordpress.tv/2023/10/06/jessica-lyschik-performance-101/
Improving website performance with caching - https://wordpress.tv/2023/07/26/improving-website-performance-with-caching/
Using A CDN To Speed Up Your Website - https://wordpress.tv/2017/10/11/gaelan-lloyd-using-a-cdn-to-speed-up-your-website/

I am still getting accustomed to GitHub and creating new pages in WordPress.org so I apologize if I am moving slowly here. Can you point me to any relevant documentation for the next step I should take here?

**Comment by rogermedia** [comment]
@javiercasares I see that there is already a page in the Handbook for Learn WordPress here https://make.wordpress.org/hosting/handbook/learn-hosting/

It seems like that is the page for this ticket?

**Comment by jayblaq** [comment]
Thank you all for reviewing.  We are moving this issue to closed.
