### ISSUE TITLE
Mention the hosting handbook on wordpress.org/hosting

### ISSUE THREAD

**Issue by Crixu** [WordPress/hosting-handbook#20]
There should be a link on wordpress.org/hosting mentioning the hosting handbook to get more attention to it.

**Comment by j-falk** [comment]
We should probably also link to https://wordpress.org/hosting/ also in the handbook maybe on https://make.wordpress.org/hosting/handbook/?

**Comment by javiercasares** [comment]
The page https://wordpress.org/hosting/ links to the requirements one https://wordpress.org/about/requirements/ and then, it has a link to the server requirements at https://make.wordpress.org/hosting/handbook/handbook/server-environment/

**Comment by tacoverdo** [comment]
Per discussion in the WCEU contributor day zoom session:
If we want to have a direct link, a ticket on the Meta trac should be created for this.

**Comment by jayblaq** [comment]
I think this is good enough: The page https://wordpress.org/hosting/ links to the requirements one https://wordpress.org/about/requirements/ and then, it has a link to the server requirements at https://make.wordpress.org/hosting/handbook/handbook/server-environment/

Shall we close this 4 year old issue?
