### ISSUE TITLE
Add direct link to #hosting-community slack channel in callout

### ISSUE THREAD

**Issue by j-falk** [WordPress/hosting-handbook#21]
All links in the git repo are already linking references to the #hosting-community Slack channel, but the callout on the bottom of https://make.wordpress.org/hosting/handbook/ don't have it.

![WordPress_Hosting_Handbook_–_Make_WordPress_Hosting](https://user-images.githubusercontent.com/1665833/83772072-44000500-a683-11ea-91ac-aa399d6312c1.png)

Might be a small thing but the easier we can get people to the Slack channel the better, but I can't seem to find how to edit that in the repo.

**Comment by javiercasares** [comment]
@getsource I don't know how to do that, because that text is not in the markdown page.

**Comment by getsource** [comment]
In this case, would it be better to change the text to point folks to how to edit in this repo?
I'll take a look at where that text might live in the make handbook.

**Comment by getsource** [comment]
It looks like it's in a shortcode over there, so I believe we can change it.

Here's the contents:
`[info]If you’re interested in improving this handbook, leave a message in the #hosting-community channel of the <a href="https://make.wordpress.org/chat/">official WordPress Slack</a>.[/info]`
