### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by Kudratullah** [WordPress/hosting-handbook#236]
Should not it be WordPress 6.5 ([hosting-handbook/server-environment.md#L34](https://github.com/WordPress/hosting-handbook/blob/4c158c1895d39c91229ff67dfaf93c53129390ee/server-environment.md?plain=1#L34))

https://github.com/WordPress/hosting-handbook/blob/4c158c1895d39c91229ff67dfaf93c53129390ee/server-environment.md?plain=1#L28-L35

**Comment by javiercasares** [comment]
Will be fixed with #245
