### ISSUE TITLE
Add requirement for Gutenberg

### ISSUE THREAD

**Issue by Crixu** [WordPress/hosting-handbook#29]
A lot of hosters use mod_security to block unwanted methods and traffic. In the "old" days methods like PUT or DELETE weren't needed but Gutenberg is using the REST API and those methods. We should add a section to the server environment page about this.

**Comment by javiercasares** [comment]
What should be add?
- CONNECT (not sure)
- DELETE (sure)
- GET (sure)
- HEAD (maybe)
- OPTIONS (maybe)
- POST (sure)
- PUT (i think Gutenberg needs this)
- TRACE (not sure)
