### ISSUE TITLE
research make teams 'getting started at contributor day' pages

### ISSUE THREAD

**Issue by kittenkamala** [WordPress/hosting-handbook#3]
This ticket is related to the team updates needed for WCEU Online 2020 Contributor Day

https://make.wordpress.org/updates/2020/04/15/wordcamp-europe-2020-contributor-day-update/

The Hosting Team needs to: 

Update the “Getting Started at a Contributor Day” page in your handbook (example from Polyglots). This page should give a general idea of what and how the team works during Contributor Days. If you don’t have such a page, can you please create one.

**Comment by getsource** [comment]
Yesterday, I [published the draft noted earlier](https://make.wordpress.org/hosting/handbook/handbook/get-involved/), and ported it to this repo.

This ticket is open now, to make it easier for us to review+merge other changes from @javiercasares' audit: https://meta.trac.wordpress.org/ticket/5247

**Comment by javiercasares** [comment]
Done #114
