### ISSUE TITLE
Some additional sections to the Security documentation (security.md)

### ISSUE THREAD

**Issue by pharar** [WordPress/hosting-handbook#30]
Personally, being intended this book to hosting, I would enforce some points in the documentation about security:

- **SSL** 
Here would be awesome to have a section talking about .htaccess, adding the different strategies needed to be added in order to force HTTPS. It is named in the central WordPress documentation. These are a couple of examples:
_Default HTTPS redirection_
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteCond %{HTTP_HOST} ^(www\.)?domain\.com$ [NC]
RewriteRule ^(.*)$ https://www.domain.com/$1 [L,R=301]
</IfModule>
```

_Security policy_ (Could break content loaded from http-based source):
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP_HOST} ^(www\.)?domain\.com$ [NC]
RewriteRule .* - [E=UPGRADE]
  <IfModule mod_headers.c>
  Header always set Content-Security-Policy "upgrade-insecure-requests;" env=UPGRADE
  </IfModule>
</IfModule>
```

- Apache/Nginx boilerplate with some highlighting points to have in mind, for example these directives: 
   - `Options +Indexes`
   - `AllowOverride all`

- The use of `admin` user. A random name would be preferible.

- Backups:
   -  Remember to Not to storage backups in the site
   -  Add any kind of exclusion for robots, like rules to avoid .zip, .txt., sql files.
   
- Old fashion Firewalls block the access to the wp-json URI, the RestAPI, so Gutenberg editor gets a lot of issues till this access is granted again. It should be in mind. 
More info in the following link:
https://developer.wordpress.org/rest-api/reference

WiP, additions are more than welcome.
Thanks!

**Comment by javiercasares** [comment]
I ave some documentation may be useful if we want to add at https://wpalojamiento.com/infraestructura/instalacion/htaccess/

**Comment by javiercasares** [comment]
#15

**Comment by javiercasares** [comment]
Moved to:
https://github.com/WordPress/Advanced-administration-handbook/issues/154
