### ISSUE TITLE
Create "About us"

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#32]
As other teams have, we should have an "About us" section that explains about us and separates it from the "Get Involved" section that could be a section.

**Comment by getsource** [comment]
How do you think the Index should be separate from "About us"?

Basically going into more details on the About us?

**Comment by getsource** [comment]
Related: https://github.com/WordPress/hosting-handbook/issues/27

**Comment by javiercasares** [comment]
It was a proposal at the Contributor Day. As they said, our Handbook is a bit different from the other ones, because usually it "talks to contributors" and ours talks "to hosters (and others)" so, it's more like documentation.

This is why they think we should have a "Who we are and what we do (as a Team)", then the "Get Involved" and finally the Handbook and Tests information/tutorials.

It was an idea, I think it's good. We can also add this "Who we are" at the index page.
