### ISSUE TITLE
Add a glossary / jargon for the Handbook

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#53]
Should we add a technical "jargon" section in the handbook? Like

https://make.wordpress.org/core/handbook/glossary/

https://make.wordpress.org/marketing/handbook/wordpress-jargon-glossary/

Could be useful.

**Comment by getsource** [comment]
Yes, it'd be really cool to have a glossary! I wonder if we need to do anything special to get the custom mouse-over popups that show up for glossary in other handbooks.

**Comment by javiercasares** [comment]
First idea, based on Glossary from Core and Marketing

https://docs.google.com/spreadsheets/d/1mm8EciUkzcppwD1RL45hQ08kimS36sL2zbzkPY-TBDY/

**Comment by getsource** [comment]
Looks like a good start to me -- thanks for putting it together!

**Comment by javiercasares** [comment]
Added to the Handbook, via the Glossary plugin / shortcode.

https://make.wordpress.org/hosting/handbook/handbook/glossary/

We can do changes within the site.
