### ISSUE TITLE
WordPress + PHP Matrix

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#54]
We should create a table with the relation between WordPress major version, and PHP min / max versions supported.

**Comment by getsource** [comment]
This might be helpful: https://displaywp.com/wordpress-minimum-php-version/

Looks like the note about the increase to 7.2 is incorrect, but a good reference for when the other minimum bumps happened, along with links.

**Comment by fierevere** [comment]
https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
core handbook already has a chart

**Comment by getsource** [comment]
Thanks @fierevere ! 

I'm glad to see there is reference a reference, although I'm sorry there was so much work put into this one.

Personally, I think it'd make sense to link to the Core one from the Hosting handbook, since that's where those decisions are made.

**Comment by javiercasares** [comment]
Yes, but this is a different chart.

The Core chart is a WordPress compatibility chart, so "What versions are WordPress compatible?"

The new "hosting" table is to know "what versions of software were available at the time of the release... for example, WordPress 5.9 is compatible with PHP 7.0, but when it was released, this version of PHP was not recommended because it has security issues, but it is also compatible with PHP 7.4, who is available at the time this version was...

It's more a "hosting" vision, than a software vision.
