### ISSUE TITLE
Content menu order

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#6]
Right now the menu order is alphabetically. Should we order it with more _sense_? Like:

1. Get Involved
2. Server Environment
3. Performance
4. Security
5. Reliability

This order should give the user a better navigation (from top to bottom).

**Comment by Crixu** [comment]
We worked out the following proposal for a menu structure:


- About the Hosting Team
  - What the Hosting Team Does
  - Team Reps 
  - Contributing Hosts
  - Participation
- Hosting WordPress; Info for Hosts
  - Performance
  - Reliability
  - Security
  - Server Environment
- Get Involved
  - First steps for New Contributors
    - Slack
    - Meetings: What to expect
      - Meeting times and days
      - Wave in
      - Topics discussed
      - Open Floors
   - Meetings: Taking notes
    - wp-admin Access
    - Writing in the WordPress voice 
  - Getting Started at a Contributor Day
    - Working Groups
    - New Contributor Onboarding
    - What to expect at WCEU
    - Office hours
  - Contributing to the Handbook
  - Contributing with code
    - Git
    - Coding standards
    - Making Commits: What to Expect
- Related WordPress Teams
- Other documents
- Team Pledges
- PHPUnit Tests
  - What is it
    - Runner
    - Reporter
  - Setting up on hosting systems
    - Local Environment Recommendations
    - Travis, Circle or other CI 
  - How to report

**Comment by Crixu** [comment]
maybe we could start creating this structure here on github to reassemble it later on https://make.wordpress.org/hosting/handbook/

**Comment by javiercasares** [comment]
I think the page order must be changed inside the WordPress (page order) manually.

**Comment by javiercasares** [comment]
Done
