### ISSUE TITLE
Create the Glossary Page

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#67]
_Copy_ the actual Glossary content into a MD page.

**Comment by Crixu** [comment]
How should we handle this? 
Currently the glossar page will be automatically generated from the custom post type. 
maybe it makes sense to have a way to add new things easily but don't have the need to copy/paste/format everything which is already in there?

**Comment by pfefferle** [comment]
Is it important to map this to GitHub? Why not simply define a process of extending/changing entries using GitHub issue?

**Comment by javiercasares** [comment]
Published at https://make.wordpress.org/hosting/handbook/handbook/glossary/
